import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fdf8',
  },
  headerGradient: {
    paddingTop: 40,
    paddingBottom: 30,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    backgroundColor: '#2E7D32',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  backButton: {
    width: 45,
    height: 45,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextContainer: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: 'white',
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
    marginTop: 4,
    fontWeight: '400',
  },
  placeholder: {
    width: 45,
  },
  content: {
    flex: 1,
  },
  routeInfoCard: {
    backgroundColor: 'white',
    marginHorizontal: 16,
    marginVertical: 16,
    paddingVertical: 20,
    paddingHorizontal: 18,
    borderRadius: 18,
    elevation: 4,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    borderLeftWidth: 5,
    borderLeftColor: '#43A047',
  },
  routeRow: {
    flexDirection: 'row',
  },
  routeIconContainer: {
    alignItems: 'center',
    marginRight: 18,
  },
  originDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#43A047',
    borderWidth: 2,
    borderColor: '#2E7D32',
  },
  routeLine: {
    width: 3,
    height: 35,
    backgroundColor: '#C8E6C9',
    marginVertical: 6,
  },
  routeTextContainer: {
    flex: 1,
    justifyContent: 'space-between',
  },
  locationItem: {
    marginBottom: 12,
  },
  locationLabel: {
    fontSize: 12,
    color: '#2E7D32',
    marginBottom: 4,
    fontWeight: '600',
    opacity: 0.7,
  },
  locationText: {
    fontSize: 16,
    color: '#1B5E20',
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  mapContainer: {
    height: 250,
    marginHorizontal: 16,
    marginVertical: 16,
    borderRadius: 18,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  busListSection: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  busCard: {
    backgroundColor: 'white',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 16,
    elevation: 4,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    borderTopWidth: 4,
    borderTopColor: '#43A047',
  },
  busHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  busIconContainer: {
    width: 65,
    height: 65,
    borderRadius: 16,
    backgroundColor: '#E8F5E9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    borderWidth: 2,
    borderColor: '#C8E6C9',
  },
  busInfoContainer: {
    flex: 1,
  },
  busNumber: {
    fontSize: 19,
    fontWeight: '700',
    color: '#1B5E20',
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  busDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  busDetailText: {
    fontSize: 14,
    color: '#555',
    marginLeft: 7,
    fontWeight: '500',
  },
  priceContainer: {
    alignItems: 'flex-end',
  },
  priceLabel: {
    fontSize: 12,
    color: '#2E7D32',
    opacity: 0.7,
    fontWeight: '500',
  },
  priceText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#43A047',
    marginTop: 4,
  },
  busFooter: {
    borderTopWidth: 1.5,
    borderTopColor: '#E8F5E9',
    paddingTop: 16,
  },
  busFeatures: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 22,
  },
  featureText: {
    fontSize: 13,
    color: '#555',
    marginLeft: 6,
    fontWeight: '500',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  trackButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8F5E9',
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#43A047',
  },
  trackButtonText: {
    color: '#2E7D32',
    fontSize: 15,
    fontWeight: '700',
    marginLeft: 6,
    letterSpacing: 0.3,
  },
  bookButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#43A047',
    paddingVertical: 13,
    borderRadius: 12,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  bookButtonText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '700',
    marginLeft: 6,
    letterSpacing: 0.3,
  },
  errorContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  errorText: {
    fontSize: 16,
    color: '#F44336',
    marginTop: 15,
    textAlign: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1B5E20',
    marginTop: 15,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#2E7D32',
    marginTop: 8,
    textAlign: 'center',
    paddingHorizontal: 30,
    opacity: 0.7,
  },
  bottomNavigation: {
    flexDirection: 'row',
    backgroundColor: 'white',
    paddingVertical: 12,
    paddingBottom: 18,
    borderTopWidth: 1.5,
    borderTopColor: '#E8F5E9',
    elevation: 8,
    shadowColor: '#2E7D32',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
  },
  navButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navText: {
    fontSize: 12,
    color: '#999',
    marginTop: 4,
  },
  activeNavText: {
    color: '#4CAF50',
    fontWeight: 'bold',
  },
});

export default styles;
