import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

// Responsive dimensions
const isSmallScreen = width < 375;
const SEAT_SIZE = isSmallScreen ? 36 : 44;
const SEAT_MARGIN = isSmallScreen ? 4 : 6;
const HEADER_FONT_SIZE = isSmallScreen ? 24 : 28;
const TITLE_FONT_SIZE = isSmallScreen ? 15 : 17;

// Green and white color scheme
const GREEN_PRIMARY = '#2E7D32';
const GREEN_SECONDARY = '#43A047';
const GREEN_LIGHT = '#E8F5E9';
const GREEN_LIGHTER = '#C8E6C9';
const WHITE = '#fff';
const TEXT_DARK = '#1B5E20';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: WHITE,
  },
  headerSection: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: GREEN_LIGHT,
  },
  head: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  backArrowContainer: {
    width: 46,
    height: 46,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: WHITE,
    marginRight: 12,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1.5,
    borderColor: GREEN_LIGHTER,
  },
  titleWrapper: {
    flex: 1,
    justifyContent: 'center',
  },
  title: {
    fontSize: HEADER_FONT_SIZE,
    fontWeight: '700',
    color: GREEN_PRIMARY,
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: isSmallScreen ? 12 : 14,
    color: TEXT_DARK,
    opacity: 0.7,
    fontWeight: '400',
  },
  busInfoCard: {
    marginHorizontal: 12,
    marginBottom: 16,
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 14,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    borderLeftWidth: 4,
    borderLeftColor: GREEN_SECONDARY,
  },
  busInfoContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  busName: {
    fontSize: 16,
    fontWeight: '700',
    color: GREEN_PRIMARY,
    marginBottom: 4,
  },
  busDetails: {
    fontSize: 11,
    color: TEXT_DARK,
    opacity: 0.65,
    fontWeight: '500',
  },
  busDetailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    gap: 8,
  },
  detailItem: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: GREEN_LIGHT,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    borderLeftWidth: 3,
    borderLeftColor: GREEN_SECONDARY,
  },
  detailLabel: {
    fontSize: 10,
    color: TEXT_DARK,
    opacity: 0.7,
    fontWeight: '600',
    marginBottom: 4,
  },
  detailValue: {
    fontSize: 13,
    fontWeight: '700',
    color: GREEN_PRIMARY,
  },
  routeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: GREEN_LIGHTER,
  },
  routeText: {
    fontSize: 12,
    fontWeight: '600',
    color: TEXT_DARK,
    marginHorizontal: 6,
  },
  routeArrow: {
    fontSize: 12,
    color: GREEN_SECONDARY,
    fontWeight: '700',
  },
  seatsAvailableBadge: {
    backgroundColor: GREEN_SECONDARY,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    minWidth: 80,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  seatsAvailableText: {
    fontSize: 18,
    fontWeight: '700',
    color: WHITE,
  },
  seatsAvailableLabel: {
    fontSize: 10,
    color: WHITE,
    opacity: 0.9,
    fontWeight: '600',
    marginTop: 2,
  },
  seatLayout: {
    marginHorizontal: 12,
    marginBottom: 16,
    backgroundColor: WHITE,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 12,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  seatLayoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: GREEN_LIGHT,
  },
  seatLayoutTitle: {
    fontSize: TITLE_FONT_SIZE,
    fontWeight: '700',
    color: GREEN_PRIMARY,
    marginLeft: 8,
    letterSpacing: 0.3,
  },
  row: {
    flexDirection: 'row',
    marginBottom: isSmallScreen ? 10 : 12,
    justifyContent: 'center',
  },
  seat: {
    width: SEAT_SIZE,
    height: SEAT_SIZE,
    margin: SEAT_MARGIN,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 2.5,
    borderColor: GREEN_LIGHTER,
  },
  availableSeat: {
    backgroundColor: WHITE,
    borderColor: GREEN_SECONDARY,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  unavailableSeat: {
    backgroundColor: '#f0f0f0',
    borderColor: '#ccc',
    opacity: 0.5,
  },
  selectedSeat: {
    backgroundColor: GREEN_SECONDARY,
    borderColor: GREEN_PRIMARY,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  seatText: {
    fontSize: isSmallScreen ? 10 : 12,
    fontWeight: '700',
    color: GREEN_PRIMARY,
  },
  selectedSeatText: {
    color: WHITE,
  },
  spacer: {
    width: SEAT_SIZE + SEAT_MARGIN * 2,
    height: SEAT_SIZE,
    marginHorizontal: SEAT_MARGIN / 2,
  },
  directionIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: isSmallScreen ? 14 : 18,
    paddingTop: 12,
    borderTopWidth: 2,
    borderTopColor: GREEN_LIGHT,
  },
  directionArrow: {
    backgroundColor: GREEN_SECONDARY,
    width: 36,
    height: 36,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  directionText: {
    fontSize: isSmallScreen ? 12 : 14,
    color: GREEN_PRIMARY,
    fontWeight: '700',
    opacity: 0.85,
  },
  legendSection: {
    flexDirection: isSmallScreen ? 'column' : 'row',
    justifyContent: 'space-around',
    alignItems: isSmallScreen ? 'flex-start' : 'center',
    marginHorizontal: 12,
    marginBottom: 14,
    backgroundColor: GREEN_LIGHT,
    borderRadius: 14,
    paddingVertical: isSmallScreen ? 12 : 14,
    paddingHorizontal: 12,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: isSmallScreen ? 1 : undefined,
    marginBottom: isSmallScreen ? 8 : 0,
  },
  legendBox1: {
    width: 18,
    height: 18,
    backgroundColor: WHITE,
    borderWidth: 2,
    borderColor: GREEN_SECONDARY,
    borderRadius: 5,
    marginRight: 6,
  },
  legendBox2: {
    width: 18,
    height: 18,
    backgroundColor: '#f0f0f0',
    borderWidth: 2,
    borderColor: '#ccc',
    borderRadius: 5,
    marginRight: 6,
    opacity: 0.5,
  },
  legendBox3: {
    width: 18,
    height: 18,
    backgroundColor: GREEN_SECONDARY,
    borderWidth: 2,
    borderColor: GREEN_PRIMARY,
    borderRadius: 5,
    marginRight: 6,
  },
  legendText: {
    fontSize: isSmallScreen ? 11 : 12,
    color: GREEN_PRIMARY,
    fontWeight: '600',
  },
  selectedSeatsCard: {
    marginHorizontal: 12,
    marginBottom: 14,
    backgroundColor: GREEN_LIGHT,
    borderRadius: 14,
    padding: 12,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  selectedSeatsTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: GREEN_PRIMARY,
    marginBottom: 10,
  },
  selectedSeatsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  selectedSeatBadge: {
    backgroundColor: GREEN_SECONDARY,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 7,
    marginRight: 6,
    marginBottom: 6,
  },
  selectedSeatText: {
    color: WHITE,
    fontWeight: '700',
    fontSize: isSmallScreen ? 11 : 12,
  },
  continueButton: {
    marginHorizontal: 12,
    marginBottom: 22,
    height: 50,
    borderRadius: 12,
    backgroundColor: GREEN_SECONDARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  disabledButton: {
    opacity: 0.5,
  },
  continueText: {
    fontSize: isSmallScreen ? 16 : 18,
    fontWeight: '700',
    color: WHITE,
    letterSpacing: 0.3,
  },
  buttonIcon: {
    marginLeft: 8,
  },
});
