import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

// Responsive dimensions
const isSmallScreen = width < 375;
const SEAT_SIZE = isSmallScreen ? 36 : 44;
const SEAT_MARGIN = isSmallScreen ? 4 : 6;
const HEADER_FONT_SIZE = isSmallScreen ? 24 : 28;
const TITLE_FONT_SIZE = isSmallScreen ? 15 : 17;

// Green and white color scheme
const GREEN_PRIMARY = '#2E7D32';
const GREEN_SECONDARY = '#43A047';
const GREEN_LIGHT = '#E8F5E9';
const GREEN_LIGHTER = '#C8E6C9';
const WHITE = '#fff';
const TEXT_DARK = '#1B5E20';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: WHITE,
    paddingTop: 15,
  },
  headerSection: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: GREEN_LIGHT,
  
  },
  head: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  backArrowContainer: {
    width: 46,
    height: 46,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: WHITE,
    marginRight: 12,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1.5,
    borderColor: GREEN_LIGHTER,
  },
  titleWrapper: {
    flex: 1,
    justifyContent: 'center',
  },
  title: {
    fontSize: HEADER_FONT_SIZE,
    fontWeight: '700',
    color: GREEN_PRIMARY,
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: isSmallScreen ? 12 : 14,
    color: TEXT_DARK,
    opacity: 0.7,
    fontWeight: '400',
  },
  busInfoCard: {
    marginHorizontal: 16,
    marginBottom: 14,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: "#0ba425ff",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  busInfoGradient: {
    padding: 14,
  },
  busNumberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  busNumber: {
    fontSize: 18,
    fontWeight: '700',
    color: WHITE,
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  routeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  routeLocationBox: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  routeLocationText: {
    fontSize: 12,
    fontWeight: '600',
    color: WHITE,
    marginLeft: 6,
  },
  routeArrowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  routeDottedLine: {
    width: 10,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  routeDotStart: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4CAF50',
    borderWidth: 1.5,
    borderColor: WHITE,
  },
  routeDotEnd: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FF5722',
    borderWidth: 1.5,
    borderColor: WHITE,
  },
  seatStatsRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  seatStatBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  seatStatNumber: {
    fontSize: 20,
    fontWeight: '800',
    color: GREEN_PRIMARY,
  },
  seatStatLabel: {
    fontSize: 11,
    color: TEXT_DARK,
    fontWeight: '600',
  },
  seatStatDivider: {
    width: 1,
    height: 30,
    backgroundColor: GREEN_LIGHTER,
  },
  seatsAvailableBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: 'center',
    minWidth: 70,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  seatsAvailableText: {
    fontSize: 24,
    fontWeight: '800',
    color: WHITE,
  },
  seatsAvailableLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.9)',
    fontWeight: '600',
    marginTop: 2,
  },
  seatLayout: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: WHITE,
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: GREEN_LIGHTER,
  },
  seatLayoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  steeringIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: GREEN_SECONDARY,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  seatLayoutTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: GREEN_PRIMARY,
    letterSpacing: 0.3,
  },
  busFront: {
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: GREEN_LIGHT,
  },
  busFrontWindow: {
    width: 80,
    height: 20,
    borderRadius: 10,
    backgroundColor: GREEN_LIGHT,
    borderWidth: 2,
    borderColor: GREEN_SECONDARY,
  },
  busRear: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 2,
    borderTopColor: GREEN_LIGHT,
  },
  busRearText: {
    fontSize: 12,
    color: GREEN_SECONDARY,
    fontWeight: '600',
    marginLeft: 6,
  },
  row: {
    flexDirection: 'row',
    marginBottom: isSmallScreen ? 10 : 12,
    justifyContent: 'center',
  },
  seat: {
    width: SEAT_SIZE,
    height: SEAT_SIZE + 8,
    margin: SEAT_MARGIN,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: GREEN_LIGHTER,
    paddingTop: 2,
  },
  seatIconContainer: {
    marginBottom: 2,
  },
  availableSeat: {
    backgroundColor: WHITE,
    borderColor: GREEN_SECONDARY,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  unavailableSeat: {
    backgroundColor: '#f5f5f5',
    borderColor: '#ddd',
    borderStyle: 'dashed',
  },
  selectedSeat: {
    backgroundColor: GREEN_SECONDARY,
    borderColor: GREEN_PRIMARY,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  seatText: {
    fontSize: isSmallScreen ? 9 : 10,
    fontWeight: '700',
    color: GREEN_PRIMARY,
    marginTop: 1,
  },
  selectedSeatText: {
    color: WHITE,
  },
  spacer: {
    width: SEAT_SIZE + SEAT_MARGIN * 2,
    height: SEAT_SIZE,
    marginHorizontal: SEAT_MARGIN / 2,
  },
  directionIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: isSmallScreen ? 14 : 18,
    paddingTop: 12,
    borderTopWidth: 2,
    borderTopColor: GREEN_LIGHT,
  },
  directionArrow: {
    backgroundColor: GREEN_SECONDARY,
    width: 36,
    height: 36,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  directionText: {
    fontSize: isSmallScreen ? 12 : 14,
    color: GREEN_PRIMARY,
    fontWeight: '700',
    opacity: 0.85,
  },
  legendSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: WHITE,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: GREEN_LIGHTER,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  legendBox1: {
    width: 28,
    height: 28,
    backgroundColor: WHITE,
    borderWidth: 2,
    borderColor: GREEN_SECONDARY,
    borderRadius: 8,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  legendBox2: {
    width: 28,
    height: 28,
    backgroundColor: '#f5f5f5',
    borderWidth: 2,
    borderColor: '#ddd',
    borderStyle: 'dashed',
    borderRadius: 8,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  legendBox3: {
    width: 28,
    height: 28,
    backgroundColor: GREEN_SECONDARY,
    borderWidth: 2,
    borderColor: GREEN_PRIMARY,
    borderRadius: 8,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  legendText: {
    fontSize: 12,
    color: TEXT_DARK,
    fontWeight: '600',
  },
  selectedSeatsCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: GREEN_LIGHTER,
  },
  selectedSeatsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  selectedSeatsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: GREEN_PRIMARY,
    marginLeft: 8,
  },
  selectedSeatsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  selectedSeatBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GREEN_SECONDARY,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    gap: 6,
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  selectedSeatText: {
    color: WHITE,
    fontWeight: '700',
    fontSize: 13,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: GREEN_LIGHTER,
  },
  totalLabel: {
    fontSize: 14,
    color: TEXT_DARK,
    fontWeight: '600',
  },
  totalValue: {
    fontSize: 20,
    color: GREEN_PRIMARY,
    fontWeight: '800',
  },
  continueButton: {
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: GREEN_PRIMARY,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 5,
  },
  continueGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  disabledButton: {
    opacity: 0.6,
  },
  continueText: {
    fontSize: 16,
    fontWeight: '700',
    color: WHITE,
    letterSpacing: 0.3,
  },
  continueIconContainer: {
    marginLeft: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonIcon: {
    marginLeft: 8,
  },
});
