import { StyleSheet} from 'react-native';

const styles = StyleSheet.create({
container:{
    flex:1,
    padding:8,
   
},
backArrowContainer:{
    height:40,
    width:40,
    justifyContent:'center',
    alignItems:'center',
},
welcomeMsg:{
    justifyContent:'center',
    gap:2,
    margin:10,
    paddingTop:-10,
},
welcomeText:{
    fontSize:30,
    fontWeight:'bold',
    color:'green',
    //fontFamily:'serif',
    paddingTop:50,
    marginLeft:5,
},
p:{
    fontSize:20,
    color:'black',
    fontWeight:'bold',
    marginLeft:5,
    marginTop:-10,
},
tiImg:{
    flexDirection:'row',
    justifyContent:'center',
    alignItems:'center',
    marginHorizontal:10,
    marginRight:90
    
  },
  img:{
    fontSize:40,
    marginTop:60,
    marginLeft:10
  },
form:{
    marginVertical:40,
},
inputContainer:{
    borderWidth:1,
    borderColor:'black',
    borderRadius:5,
    height:50,
    flexDirection:'row',
    paddingHorizontal:20,
    alignItems:'center',
    marginBottom:15,
},
textInput:{
    flex:1,
    fontSize:20,
    paddingHorizontal:20,
    color:'black',
},
signUpButton:{
    height:50,
    borderRadius:5,
    alignItems:'center',
    justifyContent:'center',
    marginTop:10,
    backgroundColor: 'black',
},
buttonSignUpText:{
    fontSize:20,
    fontWeight:'bold',
    color:'white',
},
continueText:{
    textAlign:'center',
    padding:10,
    marginTop:10,
    fontSize:18,
},
googleButton:{
    borderWidth:1,
    height:50,
    borderRadius:25,
    alignItems:'center',
    justifyContent:'center',
    marginTop:10,
    backgroundColor:'white',
    flexDirection:'row',
    gap:10,
},
buttonGoogleText:{
    fontSize:20,
    fontWeight:'bold',
    color:'black',
},
googleLogo:{
    width:21,
    height:21,
},
bottomText:{
    justifyContent:'center',
    alignItems:'center',
    flexDirection:'row',
    gap:10,
    marginVertical:20,
},
alreadyAccountText:{
    fontSize:18,
    color:'black'
},
bottomLogin:{
    fontSize:20,
    fontWeight:'bold',
    color:'black',
    textDecorationLine:'underline',
},
});

export default styles;
